[package]
name = "solveknot"
version = "0.1.0"
authors = ["Jack Greenberg <theProgrammerJack@gmail.com>"]
edition = "2018"

[dependencies]
knot-solver = { path = "../knot-solver" }
structopt = "0.2"
serde = "1.0.91"
serde_derive = "1.0.91"
csv = "1.0.7"
